### ISSUE TITLE
Variable dropdown sould show lexical variables

### ISSUE THREAD

**Issue by lukeplays33** [mit-cml/blockly-plugins#20]
Hi there!
I'd likie to have the variable dropdowns to show the lexical variables instead of the standard dropdown (wich in this case does nothing and show no variables other than the one in the dropdown).
Thanks

**Comment by mark-friedman** [comment]
@lukeplays33 Your description suggests that you are using the standard Blocky custom toolbox category for variables.  Did you see the following in the [usage section of the README file](https://github.com/mit-cml/blockly-plugins/tree/main/block-lexical-variables#usage):

>Note that unlike with standard Blockly, you should not use a custom toolbox category for your variable, as this would interfere with the way that variables are declared and used with this plugin. Just create an ordinary Variables category, if you want, and place the lexical-variable-get and lexical-variable-set blocks in there.

**Comment by lukeplays33** [comment]
Hi @mark-friedman.
I know that and Read the README file before using the plugin.
But When i select a variable dropdown it still shows the "standard dropdownmenu" unlike the Lexical variables setters and getters wich do show Any lexical created variable.
Hope that is a bit more clearer to you with what i mean.
Thanks

**Comment by mark-friedman** [comment]
@lukeplays33 I'm afraid I'm still not sure what you mean.  Could you include some pictures of what you are referring to.

**Comment by lukeplays33** [comment]
Hi @mark-friedman .
i made a video wich hopefully describes the issue: https://drive.google.com/file/d/1z_XlZVFL7r5EeBEw7weXU1gn3NAntSDk/view?usp=sharing
Thanks

**Comment by mark-friedman** [comment]
@lukeplays33 Can you point me to your code that implements that `____.setTimeOut` block?  That will help me diagnose the issue.

**Comment by lukeplays33** [comment]
Sure here it is:

Blockly.Blocks['set_timeout'] = {
  init: function() {
    this.appendValueInput("NAME")
        .setCheck("Number")
        .appendField(new Blockly.FieldVariable("TimeOut"), "NAME")
        .appendField(".setTimeOut");
    this.appendValueInput("l")
        .setCheck("Boolean")
        .appendField("loops");
    this.appendStatementInput("s")
        .setCheck(null)
        .appendField("do");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(210);
 this.setTooltip("Wait the specified amount of time before performing
the next action.");
 this.setHelpUrl("");
  }};


Op wo 15 dec. 2021 om 21:43 schreef Mark Friedman ***@***.***

**Comment by mark-friedman** [comment]
@lukeplays33 I'm afraid that you can't really mix and match standard Blockly FieldVariable's with the variable fields provided by the plugin.  I would suggest just using an ordinary value input instead of the Blockly.FieldVariable and then letting the user put whatever value they want in there, which would, of course, include the variable getters provided by the plugin.  Is there any reason that you want to limit the choice of the "NAME" input to only be a variable, rather than allowing the user to put any input they want in there?

**Comment by lukeplays33** [comment]
Hi Mark,
The reason it's Limited to a variable is Because the setTimeOut block
returns An ID so the user can stop the function When loops is set to true.
But I geus i could Use a getters block as variable.
Thanks

**Comment by mark-friedman** [comment]
@lukeplays33 I'm not sure I understand.  Can you go into some more detail on what exactly you want that setTimeOut block to do and how you'd like the user to interact with it? 

I'll also point out that if you expect that in most cases a user would want to put a variable getter as the "NAME" input then you might consider putting a shadow lexical_variable_get block as the "NAME" input when you specify the setTimeOut block in the toolbox.  If you are not familiar with shadow blocks see [here](https://developers.google.com/blockly/guides/configure/web/toolbox?hl=en#shadow_blocks) in the Blockly docs.

**Comment by lukeplays33** [comment]
Hi mark i ended up with the following definition:
Blockly.Blocks['set_timeout'] = {
  init: function() {
    this.appendValueInput("NAME")
        .setCheck(null)
        .appendField("call")
        .appendField(new Blockly.FieldDropdown([[project,"OPTIONNAME"]]),
"NAME")
        .appendField(".setTimeout");
    this.appendValueInput("l")
        .setCheck("Boolean")
        .appendField("loops");
    this.appendDummyInput()
        .appendField(
            new FieldParameterFlydown('TimeoutID', true,
FieldFlydown.DISPLAY_BELOW),
            'timeout');
    this.appendStatementInput("s")
        .setCheck(null)
        .appendField("do");
      this.setInputsInline(false);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("#F3AA44");
 this.setTooltip("Wait the specified amount of time before performing the
next action.");
 this.setHelpUrl("");
  },
  withLexicalVarsAndPrefix: function(child, proc) {
    const params = this.declaredNames();
    // not arguments_ instance var
    for (let i = 0; i < params.length; i++) {
      proc(params[i], '');
    }
  },
  getVars: function() {
    return [
      this.getFieldValue('timeout'),
    ];
  },
  blocksInScope: function() {
    const doBlock = this.getInputTargetBlock('s');
    if (doBlock) {
      return [doBlock];
    } else {
      return [];
    }
  },
  declaredNames: function() {
    return [
      this.getFieldValue('timeout'),
    ];
  },
  renameVar: function(oldName, newName) {
    if (Blockly.Names.equals(oldName, this.getFieldValue('ERR_STR_VAR'))) {
      this.setFieldValue(newName, 'ERR_STR_VAR');
    }
  },
  renameBound: function(boundSubstitution, freeSubstitution) {
    const paramSubstitution = boundSubstitution.restrictDomain(
        this.declaredNames());
    this.renameVars(paramSubstitution);
    const newFreeSubstitution = freeSubstitution.extend(paramSubstitution);
    LexicalVariable.renameFree(
        this.getInputTargetBlock(this.bodyInputName), newFreeSubstitution);
  },
  renameFree: function(freeSubstitution) {
    // There shouldn't be any free variables
  },
  freeVariables: function() { // return the free variables of this block
    // There shouldn't be any free variables, so this should return an
empty set.
    // Should return the empty set: something is wrong if it doesn't!
    return new Blockly.NameSet();
  }
};

the timeoutID returns the window.setInterval method id to the user wich
then can be used to stop the timeout see image.

- Luke

Op do 16 dec. 2021 om 22:18 schreef Mark Friedman ***@***.***

**Comment by mark-friedman** [comment]
Yes, that makes sense.  I thought that that might be what what you wanted, but I couldn't really tell.

One more thing @lukeplays33 , I think that you'll want to change all the occurrences of 'ERR_STR_VAR' to 'timeout'.  It looks like you changed some but not all of them.

I'm going to close this issue, but if you feel that it is not resolved you can reopen it.
