### ISSUE TITLE
Block outside of  parent statment input dont show an warning

### ISSUE THREAD

**Issue by lukeplays33** [mit-cml/blockly-plugins#21]
Hi,
So a few minutes ago I noticed that the variables outside of the parent statement input dont show any warnings.
Asshown in the images below compared to the plugin in my project and ai2.
As you can see the get number variable block shows an warning when its outside of its parent, however the get TimeoutIId doesn't show any warning.
![screenshot (23)](https://user-images.githubusercontent.com/54947833/147817703-73f4b4e3-25ee-4564-a2ba-05ab35695735.png)
<img width="384" alt="blocks (1)" src="https://user-images.githubusercontent.com/54947833/147817709-44e1517c-8cd3-4e0f-8c78-6ee26d200731.png">

Thanks.

Kind regards,

Luke

**Comment by mark-friedman** [comment]
I'll take a look, @lukeplays33

**Comment by mark-friedman** [comment]
@lukeplays33 , you need to make sure that your block's `withLexicalVarsAndPrefix` function checks that the `child` parameter is the target block of your block's scope.  To make this clear(er) and more concrete, I think you want to change the `withLexicalVarsAndPrefix` function for your 'set_timeout' block to be the following:

```
        withLexicalVarsAndPrefix: function(child, proc) {
            if (this.getInputTargetBlock('s') === child) {
                const params = this.declaredNames();
                // not arguments_ instance var
                for (let i = 0; i < params.length; i++) {
                    proc(params[i], '');
                }
            }
        },
```
You might also need to do something like this for other, similar, block type definitions.

Needless to say, this is not at all clear from the function name and is not yet documented, so there is no obvious way that you would know this. We need to work on that ;-)

**Comment by lukeplays33** [comment]
Thanks Mark,

That fixes the issue

Op di 4 jan. 2022 om 23:55 schreef Mark Friedman ***@***.***>:
