### ISSUE TITLE
flydown does not accept custom block colours

### ISSUE THREAD

**Issue by lukeplays33** [mit-cml/blockly-plugins#24]
Hi,
When setting a custom color for the variable blocks the flydown blocks don't have the same colors
and when dragging a block out of the flydown it does have the correct color.
![Screenshot 2022-04-28 11 25 44 AM](https://user-images.githubusercontent.com/54947833/165722744-ca25cea7-44cc-4a9f-a791-b65da2acca18.png)

**Comment by mark-friedman** [comment]
@lukeplays33 Would you mind specifying what you've done to set a custom color for the variable blocks?

**Comment by lukeplays33** [comment]
Sure Mark,
I've used the documentation(
https://developers.google.com/blockly/guides/configure/web/themes#using_themes
)

and ended up with something like this:

https://github.com/lukeplays33/Sketch/blob/c93ba2aa93e0f8111d94996c34257bfa7255fb74/src/index.js#L1807

**Comment by mark-friedman** [comment]
Thanks for the details, @lukeplays33!  I'll look into it.

**Comment by mark-friedman** [comment]
> I apologize @mark-friedman it seems the link doesn't go through for the specific Line you can find the code at Line 1807.

The link went to the line for me, it just took a little bit of time.

**Comment by mark-friedman** [comment]
@lukeplays33 I think I know what's going on and what the fix is.  Ii should have a new version of the package up in a couple of days which hopefully will fix the problem.

**Comment by mark-friedman** [comment]
- Fixed by commit 3c0367e6d754274c37335f02dea0c1f55826c011
- Part of NPM version 0.0.11 of this package ([here](https://www.npmjs.com/package/@mit-app-inventor/blockly-block-lexical-variables/v/0.0.11))

**Comment by mark-friedman** [comment]
@lukeplays33 Updating to the latest version of the plugin should fix your issue.

**Comment by lukeplays33** [comment]
Thanks Mark!!
I'll make sure to update the plugin.
