### ISSUE TITLE
Support non-default renderers

### ISSUE THREAD

**Issue by lukeplays33** [mit-cml/blockly-plugins#27]
The flydown of the lexical variables does not change to the selected render.

![Screenshot 2022-08-22 12 52 25](https://user-images.githubusercontent.com/54947833/185904515-9dac2a47-97d8-4819-950b-0c8a6b8dba44.png)

should look like:

![screenshot](https://user-images.githubusercontent.com/54947833/185904549-3ffaa28e-52e5-4d93-b977-d96ac4c2bc46.png)

injection:

const workspace = Blockly.inject("blocklyDiv2", {
    grid:
         {spacing: window.localStorage.getItem("grid"),
          length: 8,
          colour: '#ccc',
          snap: window.localStorage.getItem("snap")
         },
  trashcan: false,
  
  renderer: 'thrasos',
    
    theme: {
      'blockStyles' : {
          "logic_blocks": {
            "colourPrimary": window.Blockly.CONTROL_CATEGORY_HUE
         },
                    "loop_blocks": {
            "colourPrimary": window.Blockly.CONTROL_CATEGORY_HUE
         },
         "list_blocks": {
            "colourPrimary": window.Blockly.LIST_CATEGORY_HUE
         },
                   "math_blocks": {
            "colourPrimary": window.Blockly.MATH_CATEGORY_HUE
         },
                   "text_blocks": {
            "colourPrimary": window.Blockly.TEXT_CATEGORY_HUE
         },
                             "colour_blocks": {
            "colourPrimary": "#7F7F7F"
         },
                                                 "variable_blocks": {
            "colourPrimary": window.Blockly.VARIABLES_CATEGORY_HUE
         },
                                                 "procedure_blocks": {
            "colourPrimary": window.Blockly.FUNCTIONS_CATEGORY_HUE
         }
      },
      'componentStyles' : {
                   'flyoutOpacity': '0.0'
      },
   },

  toolbox: document.getElementById("toolbox"),

  plugins: {
    // These are both required.

    blockDragger: ScrollBlockDragger,

    metricsManager: ScrollMetricsManager
  },

  move: {
    scrollbars: {
      horizontal: true,

      vertical: true
    },

    drag: true,

    wheel: true
  },

  zoom: {
    controls: false,

    wheel: false,

    startScale: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  ) ? 0.6 : 0.9,

    maxScale: 3,

    minScale: 0.3,

    scaleSpeed: 1.2,

    pinch: false
  },
  horizontalLayout: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  ),

  toolboxPosition: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  )
    ? "end"
    : "start"
});

**Comment by mark-friedman** [comment]
@lukeplays33 I'm afraid that I don't see the difference between the `get item` block in the two pictures.  Can you describe the problem in some more detail?

**Comment by lukeplays33** [comment]
@mark-friedman.

Sure.
See this picture below where i use zelos as default render instead of thrasos.

![Screenshot 2022-08-22 20.02.04.png](https://user-images.githubusercontent.com/54947833/185989066-20547308-d6fb-49cb-855d-06a3e094a665.png)

You can see here that it only changes the colors a bit but not it's form.

**Comment by mark-friedman** [comment]
Ah yes.  I'm afraid that there is not currently support for renderers other than the default one.  I'm not sure how difficult that would be.  I'll look into it.
