### ISSUE TITLE
Maximum call stack size exceeded when using a localized text and global variable

### ISSUE THREAD

**Issue by TimeBather** [mit-cml/blockly-plugins#29]
# Error:
```
Uncaught RangeError: Maximum call stack size exceeded
    at new InputConnection$$module$build$src$core$renderers$measurables$input_connection (input_connection.ts:43:3)
    at new StatementInput$$module$build$src$core$renderers$measurables$statement_input (statement_input.ts:37:5)
    at new StatementInput$$module$build$src$core$renderers$geras$measurables$statement_input (statement_input.ts:38:5)
    at RenderInfo$$module$build$src$core$renderers$geras$info.addInput_ (info.ts:93:31)
    at RenderInfo$$module$build$src$core$renderers$geras$info.createRows_ (info.ts:212:12)
    at RenderInfo$$module$build$src$core$renderers$geras$info.measure (info.ts:165:10)
    at Renderer$$module$build$src$core$renderers$geras$renderer.render (renderer.ts:284:10)
    at BlockSvg$$module$build$src$core$block_svg.render (block_svg.ts:1670:36)
    at BlockSvg$$module$build$src$core$block_svg.render (block_svg.ts:1676:23)
    at FieldLexicalVariable.forceRerender (field.ts:946:39)

FieldLexicalVariable.getNamesInScope	@	field_lexical_variable.js:203
FieldLexicalVariable.getNamesInScope	@	field_lexical_variable.js:197
FieldLexicalVariable.dropdownCreate	@	field_lexical_variable.js:288
checkDropDownContainsValidValue	@	warningHandler.js:114
checkErrors	@	warningHandler.js:51
FieldLexicalVariable.dropdownChange	@	field_lexical_variable.js:421
setValue	@	field.ts:978
setValue	@	field_lexical_variable.js:114
checkDropDownContainsValidValue	@	warningHandler.js:128
checkErrors	@	warningHandler.js:51
FieldLexicalVariable.dropdownChange	@	field_lexical_variable.js:421
setValue	@	field.ts:978
setValue	@	field_lexical_variable.js:114
```

# Enviornment and related Codes
```
Blockly.Msg['LANG_VARIABLES_GLOBAL_PREFIX'] = '[全局变量]';
```
Then, when we place a global variable declaration and a variable-read block,then change the variable dropdown into the global variable , the problem occurs.

# Analysis for this bug
First , the dropdown updated ,and trigged `dropdownChange`
```js
FieldLexicalVariable.dropdownChange = function(text) {
  if (text) {
    this.doValueUpdate_(text);
    const topWorkspace = this.sourceBlock_.workspace.getTopWorkspace();
    if (topWorkspace.getWarningHandler) {
      topWorkspace.getWarningHandler().checkErrors(this.sourceBlock_);
    }
  }
  // window.setTimeout(Blockly.Variables.refreshFlyoutCategory, 1);
};
```
Then , in some steps, the doValueUpdate calls a function called `FieldLexicalVariable.setValue` , it doesn't supporting the localize
```js
setValue(text) {
    if (text && text !== " ") {
      const parts = text.split(" ");
      if (parts.length == 2 && parts[0] !== "global") {
        text = "global " + parts[1];
      }
    }
    super.setValue(text);
  }
```
So the setValue update the text again and again , until the JavaScript engine throw an Error because the stack size exceed.

**Comment by mark-friedman** [comment]
Thanks for the bug report, @TimeBather!  I think I know the likely cause.

**Comment by mark-friedman** [comment]
@TimeBather Sorry that it took so long for me to get this fixed.  I think I have it done.  Before I release it to npm, could you please test it in your environment for me?  I've created an `npm pack` file for you to use and attached it to this message (with a link below).  The easiest way to use it would probably be to download the file to the directory containing you project and type the following at the command line: 
```
npm install mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz
```

Let me know how it goes!

[mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz](https://github.com/mit-cml/blockly-plugins/files/10829645/mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz)

**Comment by TimeBather** [comment]
Thank you for fixing it. But it seems that in some edge cases, this problem still exists.
![image](https://user-images.githubusercontent.com/25410512/221347244-06293fee-26be-402d-808c-b19ed8e7acf2.png)
## Steps to reproduce
1. Add a global variable declaration and a get variable block.
![image](https://user-images.githubusercontent.com/25410512/221347530-193cb2ec-bc80-4941-88bc-4f1b1aab0765.png)

2. Remove the variable name
![image](https://user-images.githubusercontent.com/25410512/221347538-9c50eed6-0c03-4e9b-b2dc-edd72eb40901.png)

3. And the name of the variable get will changed to `global _` , and the problem occured
![image](https://user-images.githubusercontent.com/25410512/221347544-3f12a705-b638-4b71-9fa1-c14817eccce6.png)
![image](https://user-images.githubusercontent.com/25410512/221347548-2f87b227-a4c1-47c9-b160-3d8143e30b68.png)

**Comment by mark-friedman** [comment]
Thanks for testing and finding the error case, @TimeBather!  I'll take a look and hopefully get back to you soon with a revised, fixed, package.

**Comment by mark-friedman** [comment]
@TimeBather Would you mind trying to re-install and test the following new version of the packed file?

[mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz](https://github.com/mit-cml/blockly-plugins/files/10876925/mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz)

**Comment by TimeBather** [comment]
I think it still does not solve the problem.
If I change the variable names in the title to empty, it still throws maximum call stack size exceeded errors.
But if I click the dropdown of the get variable menu, and then close it without choosing, it recovered.

## Reproduction
![image](https://user-images.githubusercontent.com/25410512/222952290-bf168b85-2128-48b2-89cc-0ed0a1e57209.png)
![image](https://user-images.githubusercontent.com/25410512/222952295-c1952b29-bda5-4636-be0f-a618f1fec99d.png)
![image](https://user-images.githubusercontent.com/25410512/222952345-18649b76-9d30-4682-9d53-0c46158d2c35.png)
 - [V] I did not click it, but it were automatically selected
![image](https://user-images.githubusercontent.com/25410512/222952351-6423b4c9-cf4d-44ce-b981-a77d294647dd.png)

**Comment by mark-friedman** [comment]
Thanks again for testing, @TimeBather.  I'll take another look.

**Comment by mark-friedman** [comment]
@TimeBather, I'm not seeing the behavior that you mention with the latest fixed version of the package.  I wonder if there was some cacheing that interfered with the fix.  Can you please re-download the `npm  pack` file from here: [mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz](https://github.com/mit-cml/blockly-plugins/files/10876925/mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz) then clear your npm files and cache and re-install:
```
$ rm -rf node_modules
$ npm cache clean
$ npm install
$ npm install mit-app-inventor-blockly-block-lexical-variables-0.0.13.tgz
```

**Comment by TimeBather** [comment]
I'm sorry that I forget to clean the cache of my package manager. And it works!
Thank you for fixing it.

**Comment by mark-friedman** [comment]
The fix for this has been merged and has been published to the NPM package registry.
