### ISSUE TITLE
Make this plugin compatible with Blockly 10

### ISSUE THREAD

**Issue by pierrickgrand** [mit-cml/blockly-plugins#36]
Hello, 
When using this plugin with the latest Blockly version (10.1.3), using the provided example' toolbox , a click on the variables cathegory make an error appear : (see the screenshot bellow) 
![lexical variables error](https://github.com/mit-cml/blockly-plugins/assets/9553846/44652ae3-f10f-41c7-be87-f6f19b5bb0de)

this error comes from the line 405 of "lexical-variables.js":

![Capture d'écran 2023-09-11 101210](https://github.com/mit-cml/blockly-plugins/assets/9553846/f13c66b8-38bb-44ae-8b43-436b5d5b3ab5)
Thanks for this cool plugin

**Comment by mark-friedman** [comment]
@pierrickgrand The code has been updated to support Blockly V10 (in #32) but I haven't made a release to NPM yet.  I'll try to get to that ASAP.  In the meantime, you might want to download and build the latest plugin code and test with your app.  

Just for my own curiosity, I'd love to know more about your app!

**Comment by pierrickgrand** [comment]
@mark-friedman 
Thanks for your really quick answer, so I will wait the future NPM release impatiently :) . To answer you're question, i use this blockly plugin in a industrial software that use scripts generated by blockly to configure it's working

**Comment by mark-friedman** [comment]
@pierrickgrand Sorry for the delay.  Please try the latest version (v1.0.0) of the NPM package and let me know how it goes.

**Comment by pierrickgrand** [comment]
> @pierrickgrand Sorry for the delay. Please try the latest version (v1.0.0) of the NPM package and let me know how it goes.

@mark-friedman, I just tested the package, it seems to work really well, thanks, great job
