### ISSUE TITLE
support unpkg way use this plugin

### ISSUE THREAD

**Issue by mlzboy** [mit-cml/blockly-plugins#47]
I checked the blockly group https://groups.google.com/g/blockly/c/V4RJ9o03qyQ?pli=1 seems this plugin is lack of way under unpkg.

use codepen.io is easy to debug and test, hope add this feature.Most Blockly document for quickstart use unpkg,it's easy to start.

**Comment by mark-friedman** [comment]
The current version of the lexical block plugin now works with unpkg using the following script tag:
```
<script src="https://unpkg.com/@mit-app-inventor/blockly-block-lexical-variables/dist/index.js"></script>
```
 You can see some example code in the ["works-with-unpkg" branch](https://github.com/mit-cml/lexical-variable-demo/tree/works-with-unpkg) of the lexical blocks plugin demo.

**Comment by mark-friedman** [comment]
Feel free to re-open this if you run into any difficulties.
